# staging-specific moonshine configuration
#
# You can set anything here that you might normally put in config/moonshine.yml, but will only apply to staging

# Primary domain application will be accessed as 
:domain: staging.bostonrb.org

# Domain aliases for applaction. One common use of this is for asset hosts.
#:domain_aliases:
#  - assets1.staging.bostonrb.org
#  - assets2.staging.bostonrb.org
